### ISSUE TITLE
deployed Bug！

### ISSUE THREAD

**Issue by niuniu688** [gitover22/captcha_recognition#1]
When the vgg model is deployed, an error message occurs and the model file cannot be loaded！

**Comment by gitover22** [comment]
> When the vgg model is deployed, an error message occurs and the model file cannot be loaded！

hi，could you please describe the problem you encountered in detail? I am not sure what you mean, whether it is the file directory problem, you can check whether the file of your trained model is complete

**Comment by niuniu688** [comment]
> > When the vgg model is deployed, an error message occurs and the model file cannot be loaded！
> 
> hi，could you please describe the problem you encountered in detail? I am not sure what you mean, whether it is the file directory problem, you can check whether the file of your trained model is complete

It's been solved！
